### PR TITLE
Add gradient to buttons matching Qt Breeze

### PR DESCRIPTION
**Pull request by ThisIsFroggie**
This commit changes the button in the Breeze GTK2 theme to match the buttons in upstream Breeze.

It adds a gradient to these, and changes the shadow to more closelly resemble the upstream one.

It also changes the insensitive buttons so they are darker and at the same time semi-transparent, like in upstream Breeze.

### CODE REVIEW

**Comment by ghost** [comment]
As the .png files are built from assets.svg, that is where you would want to make these modifications and subsequently run the script to generate the .pngs from it. However, as dirruk1 is working on the color-effects branch, it may be best to postpone these kinds of changes until that's merged or propose the change in that branch. Sorry for the inconvenience when you've already put in the work.

**Comment by ThisIsFroggie** [comment]
That's what I did, I edited the assets.svg file and then regenerated the PNGs from the script.

And that's okay, I'll wait for when the color-effects branch merges and then I'll rebase and edit as required. :)

**Comment by ghost** [comment]
Ah, I missed it- apologies. I really appreciate the effort. Hopefully we'll be able to merge all of this soon to really polish it up, as consistency is a big focus with this theme.

**Comment by dirruk1** [comment]
In the color-effects branch buttons already have the same gradient as the upstream breeze theme

**Comment by ghost** [comment]
So they do. I guess we can close this pull request, then.

**Pull request closed without merging**
